---
title: "p8105_hw2_rac2224"
author: "Rachel Crowley"
date: "10/3/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Problem 1

Reading and cleaning the Mr. Trash Wheel dataset

```{r}
library(tidyverse)
library(readxl)
trash_data = read_excel("./data/Trashwheel.xlsx", sheet = 1, range = "A2:N408",   col_types =   NULL) 
  trash_data = janitor::clean_names(trash_data) 
  trash_data = drop_na(trash_data, dumpster) 
  trash_data = mutate(trash_data, 
                      sports_balls = round(sports_balls, digits = 0)) 
  as.integer(pull(trash_data, sports_balls))
```

Reading and cleaning precipitation datasets for 2017 and 2018

```{r}
prec2018_data = read_excel("./data/Trashwheel.xlsx", sheet = 5, range =           "A2:B14", col_types = NULL)
  prec2018_data = janitor::clean_names(prec2018_data)
  prec2018_data = mutate(prec2018_data,
                         year = "2018")
prec2017_data = read_excel("./data/Trashwheel.xlsx", sheet = 6, range =           "A2:B14", col_types = NULL)
  prec2017_data = janitor::clean_names(prec2017_data)
  prec2017_data = mutate(prec2017_data,
                         year = "2017")
```

Combining precipitation datasets and converting month to character variable

```{r}
precip_data = 
  full_join(prec2017_data, prec2018_data)
precip_data = transform(precip_data, month = month.name)
```